# Generated by Django 2.2 on 2020-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('importance', models.BooleanField(default=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
